kind: pipeline
name: default

# Pipeline for putting cloudformation files into S3 for nested stacks
steps:
  # - name: build
  #   image: eignhpants/image-builder
  #   commands:
  #     - ./build/build.sh

  - name: docker push
    image: plugins/docker
    settings:
      repo: eignhpants/docker-aws-cdk
      username:
        from_secret: dh-username
      password:
        from_secret: dh-pw
    publish:
      image: eignhpants/docker-aws-cdk
